// VENDORED COPY (T-3) — source of truth: platform-backend
// endpoint-admin-service/src/main/proto/remote_bridge.proto. Field numbers,
// package and message shapes are FROZEN by the shadow wire spec; the ONLY
// local addition is the go_package option for Go codegen. Regenerate with
// scripts/proto/generate.sh; never edit field numbers here.
// Faz 22.6 T-2a — remote-bridge wire contract (protobuf encoding of the T-1 domain records).
//
// Decided by ADR-0038 (gRPC bidi over mTLS, broker-authoritative ALLOW / agent-authoritative DENY);
// field numbers are FIXED by the shadow wire spec written in T-1a:
//   endpoint-admin-service/docs/remote-bridge-wire-contract.md
// Codex architecture thread 019eb9fb (T-2a iter: Connect=CONTROL + Data=DATA streams; KILL is a
// CONTROL envelope payload, NOT a separate RPC, so it can never be queued behind DATA backpressure).
//
// T-1 owns MEANING (records, canonicalisation, validation in
// com.example.endpointadmin.remoteaccess.bridge.contract); this file owns BYTES. The adapters in
// ...bridge.wire re-validate EVERYTHING on decode (WireContract.isValidId, pilot-capability
// default-deny) — a generated proto class never reaches the broker directly.
//
// T-2a is contract + codegen + adapters ONLY: no server, no Spring wiring, no TLS, no port.
// Stream runtime semantics (heartbeat scheduling, backpressure, KILL latency) are T-2b; real
// screen/PTY DATA payloads are T-4 (owner-pilot-gated, ADR-0034 §13/D10).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: remote_bridge.proto

package remotebridgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteBridge_Connect_FullMethodName = "/endpointadmin.remotebridge.v1.RemoteBridge/Connect"
	RemoteBridge_Data_FullMethodName    = "/endpointadmin.remotebridge.v1.RemoteBridge/Data"
)

// RemoteBridgeClient is the client API for RemoteBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// Service — two agent-initiated (outbound-only) bidi streams.
//
//	Connect : the long-lived CONTROL stream. Session control, consent, permits,
//	          KILL, heartbeats, control-plane audit events. Never-drop.
//	Data    : the DATA stream for high-volume / backpressure-prone payloads
//	          (screen frames, PTY output). Drop-tolerant. Declared in T-2a;
//	          semantically inert until T-2b/T-4.
//
// KILL travels on CONTROL (Envelope.kill). CONTROL and DATA are separate HTTP/2
// streams (T-2b may put them on separate connections) so DATA backpressure can
// never delay a KILL.
// ---------------------------------------------------------------------------
type RemoteBridgeClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
	Data(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type remoteBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteBridgeClient(cc grpc.ClientConnInterface) RemoteBridgeClient {
	return &remoteBridgeClient{cc}
}

func (c *remoteBridgeClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteBridge_ServiceDesc.Streams[0], RemoteBridge_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteBridge_ConnectClient = grpc.BidiStreamingClient[Envelope, Envelope]

func (c *remoteBridgeClient) Data(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteBridge_ServiceDesc.Streams[1], RemoteBridge_Data_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteBridge_DataClient = grpc.BidiStreamingClient[Envelope, Envelope]

// RemoteBridgeServer is the server API for RemoteBridge service.
// All implementations must embed UnimplementedRemoteBridgeServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// Service — two agent-initiated (outbound-only) bidi streams.
//
//	Connect : the long-lived CONTROL stream. Session control, consent, permits,
//	          KILL, heartbeats, control-plane audit events. Never-drop.
//	Data    : the DATA stream for high-volume / backpressure-prone payloads
//	          (screen frames, PTY output). Drop-tolerant. Declared in T-2a;
//	          semantically inert until T-2b/T-4.
//
// KILL travels on CONTROL (Envelope.kill). CONTROL and DATA are separate HTTP/2
// streams (T-2b may put them on separate connections) so DATA backpressure can
// never delay a KILL.
// ---------------------------------------------------------------------------
type RemoteBridgeServer interface {
	Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error
	Data(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedRemoteBridgeServer()
}

// UnimplementedRemoteBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteBridgeServer struct{}

func (UnimplementedRemoteBridgeServer) Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRemoteBridgeServer) Data(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Errorf(codes.Unimplemented, "method Data not implemented")
}
func (UnimplementedRemoteBridgeServer) mustEmbedUnimplementedRemoteBridgeServer() {}
func (UnimplementedRemoteBridgeServer) testEmbeddedByValue()                      {}

// UnsafeRemoteBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteBridgeServer will
// result in compilation errors.
type UnsafeRemoteBridgeServer interface {
	mustEmbedUnimplementedRemoteBridgeServer()
}

func RegisterRemoteBridgeServer(s grpc.ServiceRegistrar, srv RemoteBridgeServer) {
	// If the following call pancis, it indicates UnimplementedRemoteBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteBridge_ServiceDesc, srv)
}

func _RemoteBridge_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteBridgeServer).Connect(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteBridge_ConnectServer = grpc.BidiStreamingServer[Envelope, Envelope]

func _RemoteBridge_Data_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteBridgeServer).Data(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteBridge_DataServer = grpc.BidiStreamingServer[Envelope, Envelope]

// RemoteBridge_ServiceDesc is the grpc.ServiceDesc for RemoteBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endpointadmin.remotebridge.v1.RemoteBridge",
	HandlerType: (*RemoteBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RemoteBridge_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Data",
			Handler:       _RemoteBridge_Data_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remote_bridge.proto",
}
