// VENDORED COPY (T-3) — source of truth: platform-backend
// endpoint-admin-service/src/main/proto/remote_bridge.proto. Field numbers,
// package and message shapes are FROZEN by the shadow wire spec; the ONLY
// local addition is the go_package option for Go codegen. Regenerate with
// scripts/proto/generate.sh; never edit field numbers here.
// Faz 22.6 T-2a — remote-bridge wire contract (protobuf encoding of the T-1 domain records).
//
// Decided by ADR-0038 (gRPC bidi over mTLS, broker-authoritative ALLOW / agent-authoritative DENY);
// field numbers are FIXED by the shadow wire spec written in T-1a:
//   endpoint-admin-service/docs/remote-bridge-wire-contract.md
// Codex architecture thread 019eb9fb (T-2a iter: Connect=CONTROL + Data=DATA streams; KILL is a
// CONTROL envelope payload, NOT a separate RPC, so it can never be queued behind DATA backpressure).
//
// T-1 owns MEANING (records, canonicalisation, validation in
// com.example.endpointadmin.remoteaccess.bridge.contract); this file owns BYTES. The adapters in
// ...bridge.wire re-validate EVERYTHING on decode (WireContract.isValidId, pilot-capability
// default-deny) — a generated proto class never reaches the broker directly.
//
// T-2a is contract + codegen + adapters ONLY: no server, no Spring wiring, no TLS, no port.
// Stream runtime semantics (heartbeat scheduling, backpressure, KILL latency) are T-2b; real
// screen/PTY DATA payloads are T-4 (owner-pilot-gated, ADR-0034 §13/D10).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: remote_bridge.proto

package remotebridgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pilot capability set (ADR-0034 D8). 0 is default-deny: an unset/unknown
// capability MUST be refused by the decoder, never mapped to a pilot value.
// The non-pilot RemoteSessionCapability values (FULL_RDP, FILE_TRANSFER,
// CLIPBOARD_SYNC, PORT_FORWARD, CREDENTIAL_ENTRY, ELEVATION) stay OFF-wire.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	Capability_VIEW_ONLY              Capability = 1
	Capability_CONSTRAINED_PTY        Capability = 2
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "VIEW_ONLY",
		2: "CONSTRAINED_PTY",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED": 0,
		"VIEW_ONLY":              1,
		"CONSTRAINED_PTY":        2,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_bridge_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_remote_bridge_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{0}
}

// Pilot operation set — only the operations the pilot broker allowlists
// (RemoteBridgeBroker: SCREEN_VIEW + PTY_COMMAND) exist on the wire at all.
// 0 is default-deny.
type WireOperation int32

const (
	WireOperation_WIRE_OPERATION_UNSPECIFIED WireOperation = 0
	WireOperation_SCREEN_VIEW                WireOperation = 1
	WireOperation_PTY_COMMAND                WireOperation = 2
)

// Enum value maps for WireOperation.
var (
	WireOperation_name = map[int32]string{
		0: "WIRE_OPERATION_UNSPECIFIED",
		1: "SCREEN_VIEW",
		2: "PTY_COMMAND",
	}
	WireOperation_value = map[string]int32{
		"WIRE_OPERATION_UNSPECIFIED": 0,
		"SCREEN_VIEW":                1,
		"PTY_COMMAND":                2,
	}
)

func (x WireOperation) Enum() *WireOperation {
	p := new(WireOperation)
	*p = x
	return p
}

func (x WireOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WireOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_bridge_proto_enumTypes[1].Descriptor()
}

func (WireOperation) Type() protoreflect.EnumType {
	return &file_remote_bridge_proto_enumTypes[1]
}

func (x WireOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WireOperation.Descriptor instead.
func (WireOperation) EnumDescriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{1}
}

// Logical channel (ADR-0038 §4). 0 is default-deny: every envelope must
// declare its channel explicitly; decoders reject UNSPECIFIED.
type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED ChannelType = 0
	ChannelType_CONTROL                  ChannelType = 1
	ChannelType_DATA                     ChannelType = 2
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CONTROL",
		2: "DATA",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED": 0,
		"CONTROL":                  1,
		"DATA":                     2,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_bridge_proto_enumTypes[2].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_remote_bridge_proto_enumTypes[2]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{2}
}

// ---------------------------------------------------------------------------
// Envelope — the single frame type on both streams.
//
// Channel/payload compatibility (enforced by the T-2a adapter, tested):
//
//	CONTROL : agent_hello, session_request, consent_prompt, consent_result,
//	          operation_request, operation_permit, operation_dispatch, kill,
//	          audit_event, heartbeat, error
//	DATA    : data_frame, heartbeat, error
//
// ---------------------------------------------------------------------------
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional routing headers — empty until a session exists (e.g. AgentHello),
	// but when set they MUST pass the wire-id allowlist.
	SessionId         string      `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId          string      `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ChannelType       ChannelType `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3,enum=endpointadmin.remotebridge.v1.ChannelType" json:"channel_type,omitempty"`
	FrameSeq          int64       `protobuf:"varint,4,opt,name=frame_seq,json=frameSeq,proto3" json:"frame_seq,omitempty"`
	StreamId          string      `protobuf:"bytes,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SentAtEpochMillis int64       `protobuf:"varint,6,opt,name=sent_at_epoch_millis,json=sentAtEpochMillis,proto3" json:"sent_at_epoch_millis,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_AgentHello
	//	*Envelope_SessionRequest
	//	*Envelope_ConsentPrompt
	//	*Envelope_ConsentResult
	//	*Envelope_OperationRequest
	//	*Envelope_OperationPermit
	//	*Envelope_Kill
	//	*Envelope_AuditEvent
	//	*Envelope_Heartbeat
	//	*Envelope_DataFrame
	//	*Envelope_Error
	//	*Envelope_OperationDispatch
	//	*Envelope_DeviceKeyChallenge
	//	*Envelope_DeviceKeyAttestationResponse
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_remote_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Envelope) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *Envelope) GetFrameSeq() int64 {
	if x != nil {
		return x.FrameSeq
	}
	return 0
}

func (x *Envelope) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Envelope) GetSentAtEpochMillis() int64 {
	if x != nil {
		return x.SentAtEpochMillis
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAgentHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AgentHello); ok {
			return x.AgentHello
		}
	}
	return nil
}

func (x *Envelope) GetSessionRequest() *SessionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SessionRequest); ok {
			return x.SessionRequest
		}
	}
	return nil
}

func (x *Envelope) GetConsentPrompt() *ConsentPrompt {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConsentPrompt); ok {
			return x.ConsentPrompt
		}
	}
	return nil
}

func (x *Envelope) GetConsentResult() *ConsentResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConsentResult); ok {
			return x.ConsentResult
		}
	}
	return nil
}

func (x *Envelope) GetOperationRequest() *OperationRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OperationRequest); ok {
			return x.OperationRequest
		}
	}
	return nil
}

func (x *Envelope) GetOperationPermit() *OperationPermit {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OperationPermit); ok {
			return x.OperationPermit
		}
	}
	return nil
}

func (x *Envelope) GetKill() *Kill {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

func (x *Envelope) GetAuditEvent() *AuditEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuditEvent); ok {
			return x.AuditEvent
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetDataFrame() *DataFrame {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DataFrame); ok {
			return x.DataFrame
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetOperationDispatch() *OperationDispatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OperationDispatch); ok {
			return x.OperationDispatch
		}
	}
	return nil
}

func (x *Envelope) GetDeviceKeyChallenge() *DeviceKeyChallenge {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DeviceKeyChallenge); ok {
			return x.DeviceKeyChallenge
		}
	}
	return nil
}

func (x *Envelope) GetDeviceKeyAttestationResponse() *DeviceKeyAttestationResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DeviceKeyAttestationResponse); ok {
			return x.DeviceKeyAttestationResponse
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_AgentHello struct {
	AgentHello *AgentHello `protobuf:"bytes,10,opt,name=agent_hello,json=agentHello,proto3,oneof"`
}

type Envelope_SessionRequest struct {
	SessionRequest *SessionRequest `protobuf:"bytes,11,opt,name=session_request,json=sessionRequest,proto3,oneof"`
}

type Envelope_ConsentPrompt struct {
	ConsentPrompt *ConsentPrompt `protobuf:"bytes,12,opt,name=consent_prompt,json=consentPrompt,proto3,oneof"`
}

type Envelope_ConsentResult struct {
	ConsentResult *ConsentResult `protobuf:"bytes,13,opt,name=consent_result,json=consentResult,proto3,oneof"`
}

type Envelope_OperationRequest struct {
	OperationRequest *OperationRequest `protobuf:"bytes,14,opt,name=operation_request,json=operationRequest,proto3,oneof"`
}

type Envelope_OperationPermit struct {
	OperationPermit *OperationPermit `protobuf:"bytes,15,opt,name=operation_permit,json=operationPermit,proto3,oneof"`
}

type Envelope_Kill struct {
	Kill *Kill `protobuf:"bytes,16,opt,name=kill,proto3,oneof"`
}

type Envelope_AuditEvent struct {
	AuditEvent *AuditEvent `protobuf:"bytes,17,opt,name=audit_event,json=auditEvent,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,18,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_DataFrame struct {
	DataFrame *DataFrame `protobuf:"bytes,19,opt,name=data_frame,json=dataFrame,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ErrorFrame `protobuf:"bytes,20,opt,name=error,proto3,oneof"`
}

type Envelope_OperationDispatch struct {
	OperationDispatch *OperationDispatch `protobuf:"bytes,21,opt,name=operation_dispatch,json=operationDispatch,proto3,oneof"`
}

type Envelope_DeviceKeyChallenge struct {
	DeviceKeyChallenge *DeviceKeyChallenge `protobuf:"bytes,22,opt,name=device_key_challenge,json=deviceKeyChallenge,proto3,oneof"`
}

type Envelope_DeviceKeyAttestationResponse struct {
	DeviceKeyAttestationResponse *DeviceKeyAttestationResponse `protobuf:"bytes,23,opt,name=device_key_attestation_response,json=deviceKeyAttestationResponse,proto3,oneof"`
}

func (*Envelope_AgentHello) isEnvelope_Payload() {}

func (*Envelope_SessionRequest) isEnvelope_Payload() {}

func (*Envelope_ConsentPrompt) isEnvelope_Payload() {}

func (*Envelope_ConsentResult) isEnvelope_Payload() {}

func (*Envelope_OperationRequest) isEnvelope_Payload() {}

func (*Envelope_OperationPermit) isEnvelope_Payload() {}

func (*Envelope_Kill) isEnvelope_Payload() {}

func (*Envelope_AuditEvent) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_DataFrame) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

func (*Envelope_OperationDispatch) isEnvelope_Payload() {}

func (*Envelope_DeviceKeyChallenge) isEnvelope_Payload() {}

func (*Envelope_DeviceKeyAttestationResponse) isEnvelope_Payload() {}

// Faz 22.6 #548 Path A — broker → agent (CONTROL): a broker-nonced challenge the agent answers with a
// DeviceKeyAttestationResponse. Mirrors platform-backend remote_bridge.proto (FROZEN). ADVISORY: the agent
// signs a response over the canonical binding context derived from these fields; it trusts nothing here as auth.
type DeviceKeyChallenge struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId          string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // single-use; broker replay-cache keyed on this
	NonceB64             string                 `protobuf:"bytes,2,opt,name=nonce_b64,json=nonceB64,proto3" json:"nonce_b64,omitempty"`          // 32 random bytes, base64-std
	IssuedAtEpochMillis  int64                  `protobuf:"varint,3,opt,name=issued_at_epoch_millis,json=issuedAtEpochMillis,proto3" json:"issued_at_epoch_millis,omitempty"`
	ExpiresAtEpochMillis int64                  `protobuf:"varint,4,opt,name=expires_at_epoch_millis,json=expiresAtEpochMillis,proto3" json:"expires_at_epoch_millis,omitempty"` // short TTL
	TransportPeerKey     string                 `protobuf:"bytes,5,opt,name=transport_peer_key,json=transportPeerKey,proto3" json:"transport_peer_key,omitempty"`                // broker-observed mTLS leaf SHA-256 (binding anchor)
	ProtocolVersion      string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`                     // "device-key-session-v1"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeviceKeyChallenge) Reset() {
	*x = DeviceKeyChallenge{}
	mi := &file_remote_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceKeyChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceKeyChallenge) ProtoMessage() {}

func (x *DeviceKeyChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceKeyChallenge.ProtoReflect.Descriptor instead.
func (*DeviceKeyChallenge) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceKeyChallenge) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *DeviceKeyChallenge) GetNonceB64() string {
	if x != nil {
		return x.NonceB64
	}
	return ""
}

func (x *DeviceKeyChallenge) GetIssuedAtEpochMillis() int64 {
	if x != nil {
		return x.IssuedAtEpochMillis
	}
	return 0
}

func (x *DeviceKeyChallenge) GetExpiresAtEpochMillis() int64 {
	if x != nil {
		return x.ExpiresAtEpochMillis
	}
	return 0
}

func (x *DeviceKeyChallenge) GetTransportPeerKey() string {
	if x != nil {
		return x.TransportPeerKey
	}
	return ""
}

func (x *DeviceKeyChallenge) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

// Faz 22.6 #548 Path A — agent → broker (CONTROL): the fresh device-key session attestation answering a
// DeviceKeyChallenge. ADVISORY shape only — the broker's DEVICE_KEY_ATTESTATION_REAL verifier re-derives every
// fact (device_key_pub == mTLS leaf; device_key_sig over the binding context; certify_* TPM residency; ek_*
// chains to a pinned root). NEVER carries secrets.
type DeviceKeyAttestationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId         string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Schema              string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`                                              // "faz22.6.device-key-session.v1"
	DeviceKeyPubB64     string                 `protobuf:"bytes,3,opt,name=device_key_pub_b64,json=deviceKeyPubB64,proto3" json:"device_key_pub_b64,omitempty"` // MUST equal the mTLS leaf cert public key
	AkPubB64            string                 `protobuf:"bytes,4,opt,name=ak_pub_b64,json=akPubB64,proto3" json:"ak_pub_b64,omitempty"`
	AkNameB64           string                 `protobuf:"bytes,5,opt,name=ak_name_b64,json=akNameB64,proto3" json:"ak_name_b64,omitempty"`
	EkPubB64            string                 `protobuf:"bytes,6,opt,name=ek_pub_b64,json=ekPubB64,proto3" json:"ek_pub_b64,omitempty"`
	EkCertB64           string                 `protobuf:"bytes,7,opt,name=ek_cert_b64,json=ekCertB64,proto3" json:"ek_cert_b64,omitempty"`
	EkCertChainB64      []string               `protobuf:"bytes,8,rep,name=ek_cert_chain_b64,json=ekCertChainB64,proto3" json:"ek_cert_chain_b64,omitempty"`
	CertifyInfoB64      string                 `protobuf:"bytes,9,opt,name=certify_info_b64,json=certifyInfoB64,proto3" json:"certify_info_b64,omitempty"` // TPM2_Certify(device_key) by AK
	CertifySigB64       string                 `protobuf:"bytes,10,opt,name=certify_sig_b64,json=certifySigB64,proto3" json:"certify_sig_b64,omitempty"`
	QuoteB64            string                 `protobuf:"bytes,11,opt,name=quote_b64,json=quoteB64,proto3" json:"quote_b64,omitempty"` // TPM2_Quote; quote.extraData = the broker nonce (freshness)
	QuoteSigB64         string                 `protobuf:"bytes,12,opt,name=quote_sig_b64,json=quoteSigB64,proto3" json:"quote_sig_b64,omitempty"`
	BindingContextB64   string                 `protobuf:"bytes,13,opt,name=binding_context_b64,json=bindingContextB64,proto3" json:"binding_context_b64,omitempty"` // canonical: label‖session_id‖challenge_id‖nonce‖transport_peer_key‖expiry
	DeviceKeySigB64     string                 `protobuf:"bytes,14,opt,name=device_key_sig_b64,json=deviceKeySigB64,proto3" json:"device_key_sig_b64,omitempty"`     // device key signs binding_context
	SignedAtEpochMillis int64                  `protobuf:"varint,15,opt,name=signed_at_epoch_millis,json=signedAtEpochMillis,proto3" json:"signed_at_epoch_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeviceKeyAttestationResponse) Reset() {
	*x = DeviceKeyAttestationResponse{}
	mi := &file_remote_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceKeyAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceKeyAttestationResponse) ProtoMessage() {}

func (x *DeviceKeyAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceKeyAttestationResponse.ProtoReflect.Descriptor instead.
func (*DeviceKeyAttestationResponse) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceKeyAttestationResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetDeviceKeyPubB64() string {
	if x != nil {
		return x.DeviceKeyPubB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetAkPubB64() string {
	if x != nil {
		return x.AkPubB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetAkNameB64() string {
	if x != nil {
		return x.AkNameB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetEkPubB64() string {
	if x != nil {
		return x.EkPubB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetEkCertB64() string {
	if x != nil {
		return x.EkCertB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetEkCertChainB64() []string {
	if x != nil {
		return x.EkCertChainB64
	}
	return nil
}

func (x *DeviceKeyAttestationResponse) GetCertifyInfoB64() string {
	if x != nil {
		return x.CertifyInfoB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetCertifySigB64() string {
	if x != nil {
		return x.CertifySigB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetQuoteB64() string {
	if x != nil {
		return x.QuoteB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetQuoteSigB64() string {
	if x != nil {
		return x.QuoteSigB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetBindingContextB64() string {
	if x != nil {
		return x.BindingContextB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetDeviceKeySigB64() string {
	if x != nil {
		return x.DeviceKeySigB64
	}
	return ""
}

func (x *DeviceKeyAttestationResponse) GetSignedAtEpochMillis() int64 {
	if x != nil {
		return x.SignedAtEpochMillis
	}
	return 0
}

// Agent → broker on connect. ADVISORY ONLY — never an authorization input.
// The broker re-derives every authoritative fact through the B1.4 verifiers
// into RemoteBridgeTrustEvidence; nothing here is trusted as a boolean.
type AgentHello struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion           string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	DeviceId               string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                      // broker re-derives device trust (B1.4d)
	CertFingerprint        string                 `protobuf:"bytes,3,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"` // advisory; the broker uses the real mTLS peer cert
	AttestationEvidenceB64 string                 `protobuf:"bytes,4,opt,name=attestation_evidence_b64,json=attestationEvidenceB64,proto3" json:"attestation_evidence_b64,omitempty"`
	ProtocolVersion        string                 `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AdvertisedCapabilities []Capability           `protobuf:"varint,6,rep,packed,name=advertised_capabilities,json=advertisedCapabilities,proto3,enum=endpointadmin.remotebridge.v1.Capability" json:"advertised_capabilities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_remote_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentHello) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

func (x *AgentHello) GetAttestationEvidenceB64() string {
	if x != nil {
		return x.AttestationEvidenceB64
	}
	return ""
}

func (x *AgentHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentHello) GetAdvertisedCapabilities() []Capability {
	if x != nil {
		return x.AdvertisedCapabilities
	}
	return nil
}

// Operator console → broker (the operator never talks to the agent directly).
type SessionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceId              string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OperatorSubject       string                 `protobuf:"bytes,3,opt,name=operator_subject,json=operatorSubject,proto3" json:"operator_subject,omitempty"`
	Reason                string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedCapabilities []Capability           `protobuf:"varint,5,rep,packed,name=requested_capabilities,json=requestedCapabilities,proto3,enum=endpointadmin.remotebridge.v1.Capability" json:"requested_capabilities,omitempty"` // non-empty, all-pilot (WireContract)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_remote_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionRequest) GetOperatorSubject() string {
	if x != nil {
		return x.OperatorSubject
	}
	return ""
}

func (x *SessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SessionRequest) GetRequestedCapabilities() []Capability {
	if x != nil {
		return x.RequestedCapabilities
	}
	return nil
}

// Broker → agent: prompt the endpoint user for attended consent.
type ConsentPrompt struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OperatorDisplayName string                 `protobuf:"bytes,2,opt,name=operator_display_name,json=operatorDisplayName,proto3" json:"operator_display_name,omitempty"`
	Reason              string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Capabilities        []Capability           `protobuf:"varint,4,rep,packed,name=capabilities,proto3,enum=endpointadmin.remotebridge.v1.Capability" json:"capabilities,omitempty"`
	ExpiryEpochMillis   int64                  `protobuf:"varint,5,opt,name=expiry_epoch_millis,json=expiryEpochMillis,proto3" json:"expiry_epoch_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsentPrompt) Reset() {
	*x = ConsentPrompt{}
	mi := &file_remote_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentPrompt) ProtoMessage() {}

func (x *ConsentPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentPrompt.ProtoReflect.Descriptor instead.
func (*ConsentPrompt) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *ConsentPrompt) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsentPrompt) GetOperatorDisplayName() string {
	if x != nil {
		return x.OperatorDisplayName
	}
	return ""
}

func (x *ConsentPrompt) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConsentPrompt) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConsentPrompt) GetExpiryEpochMillis() int64 {
	if x != nil {
		return x.ExpiryEpochMillis
	}
	return 0
}

// Agent → broker: the endpoint user's consent outcome (becomes a ConsentLease).
type ConsentResult struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SessionId                 string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Granted                   bool                   `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	WindowsInteractiveSession string                 `protobuf:"bytes,3,opt,name=windows_interactive_session,json=windowsInteractiveSession,proto3" json:"windows_interactive_session,omitempty"`
	GrantedAtEpochMillis      int64                  `protobuf:"varint,4,opt,name=granted_at_epoch_millis,json=grantedAtEpochMillis,proto3" json:"granted_at_epoch_millis,omitempty"`
	ExpiryEpochMillis         int64                  `protobuf:"varint,5,opt,name=expiry_epoch_millis,json=expiryEpochMillis,proto3" json:"expiry_epoch_millis,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ConsentResult) Reset() {
	*x = ConsentResult{}
	mi := &file_remote_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentResult) ProtoMessage() {}

func (x *ConsentResult) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentResult.ProtoReflect.Descriptor instead.
func (*ConsentResult) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *ConsentResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsentResult) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *ConsentResult) GetWindowsInteractiveSession() string {
	if x != nil {
		return x.WindowsInteractiveSession
	}
	return ""
}

func (x *ConsentResult) GetGrantedAtEpochMillis() int64 {
	if x != nil {
		return x.GrantedAtEpochMillis
	}
	return 0
}

func (x *ConsentResult) GetExpiryEpochMillis() int64 {
	if x != nil {
		return x.ExpiryEpochMillis
	}
	return 0
}

// Operator console → broker: one attempted operation. command_line is empty
// for a non-PTY operation (the adapter normalises empty → null; the raw
// command travels ONLY here — a permit carries the canonical hash, never the
// raw command).
type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Operation     WireOperation          `protobuf:"varint,3,opt,name=operation,proto3,enum=endpointadmin.remotebridge.v1.WireOperation" json:"operation,omitempty"`
	CommandLine   string                 `protobuf:"bytes,4,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_remote_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *OperationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRequest) GetOperation() WireOperation {
	if x != nil {
		return x.Operation
	}
	return WireOperation_WIRE_OPERATION_UNSPECIFIED
}

func (x *OperationRequest) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

// Broker-signed (T-1b ECDSA P-256 signer), agent-verified. The signature
// covers OperationPermit.canonicalPayload() — the T-1 length-prefixed byte
// sequence over fields 1-14, independent of this protobuf encoding. The
// adapters MUST reproduce those exact bytes after a round-trip (tested
// byte-for-byte). Field 15 (signature) is NOT signed.
type OperationPermit struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Alg                  string                 `protobuf:"bytes,1,opt,name=alg,proto3" json:"alg,omitempty"`
	Kid                  string                 `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
	PermitVersion        int32                  `protobuf:"varint,3,opt,name=permit_version,json=permitVersion,proto3" json:"permit_version,omitempty"`
	PolicyVersion        string                 `protobuf:"bytes,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	DecisionId           string                 `protobuf:"bytes,5,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	SessionId            string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OperationId          string                 `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	DeviceId             string                 `protobuf:"bytes,8,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	OperatorSubject      string                 `protobuf:"bytes,9,opt,name=operator_subject,json=operatorSubject,proto3" json:"operator_subject,omitempty"`
	Capability           Capability             `protobuf:"varint,10,opt,name=capability,proto3,enum=endpointadmin.remotebridge.v1.Capability" json:"capability,omitempty"`
	CommandHash          string                 `protobuf:"bytes,11,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"` // CanonicalCommand.hash(); empty for non-command op
	IssuedAtEpochMillis  int64                  `protobuf:"varint,12,opt,name=issued_at_epoch_millis,json=issuedAtEpochMillis,proto3" json:"issued_at_epoch_millis,omitempty"`
	ExpiresAtEpochMillis int64                  `protobuf:"varint,13,opt,name=expires_at_epoch_millis,json=expiresAtEpochMillis,proto3" json:"expires_at_epoch_millis,omitempty"`
	Seq                  int64                  `protobuf:"varint,14,opt,name=seq,proto3" json:"seq,omitempty"`                                      // monotonic per-session (replay guard)
	SignatureB64         string                 `protobuf:"bytes,15,opt,name=signature_b64,json=signatureB64,proto3" json:"signature_b64,omitempty"` // broker signature over fields 1-14
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OperationPermit) Reset() {
	*x = OperationPermit{}
	mi := &file_remote_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationPermit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationPermit) ProtoMessage() {}

func (x *OperationPermit) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationPermit.ProtoReflect.Descriptor instead.
func (*OperationPermit) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *OperationPermit) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *OperationPermit) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *OperationPermit) GetPermitVersion() int32 {
	if x != nil {
		return x.PermitVersion
	}
	return 0
}

func (x *OperationPermit) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *OperationPermit) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *OperationPermit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OperationPermit) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationPermit) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *OperationPermit) GetOperatorSubject() string {
	if x != nil {
		return x.OperatorSubject
	}
	return ""
}

func (x *OperationPermit) GetCapability() Capability {
	if x != nil {
		return x.Capability
	}
	return Capability_CAPABILITY_UNSPECIFIED
}

func (x *OperationPermit) GetCommandHash() string {
	if x != nil {
		return x.CommandHash
	}
	return ""
}

func (x *OperationPermit) GetIssuedAtEpochMillis() int64 {
	if x != nil {
		return x.IssuedAtEpochMillis
	}
	return 0
}

func (x *OperationPermit) GetExpiresAtEpochMillis() int64 {
	if x != nil {
		return x.ExpiresAtEpochMillis
	}
	return 0
}

func (x *OperationPermit) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *OperationPermit) GetSignatureB64() string {
	if x != nil {
		return x.SignatureB64
	}
	return ""
}

// Broker → agent (CONTROL, T-4 CONSTRAINED_PTY): a signed permit paired with the
// plaintext command to execute. The raw command travels toward the agent ONLY here
// (never inside the permit, which carries only command_hash); it is authorization-
// NEUTRAL — the agent trusts it only after re-deriving
// CanonicalCommand.hash(command_line) == permit.command_hash against the SIGNED
// permit. command_line is empty for VIEW_ONLY. The nested permit's signed bytes are
// unchanged by this wrapper: verify the INNER permit, never the wrapper. (Wire
// shadow-spec: docs/remote-bridge-wire-contract.md; Codex 019ecd07 B2.)
type OperationDispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permit        *OperationPermit       `protobuf:"bytes,1,opt,name=permit,proto3" json:"permit,omitempty"`
	CommandLine   string                 `protobuf:"bytes,2,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationDispatch) Reset() {
	*x = OperationDispatch{}
	mi := &file_remote_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDispatch) ProtoMessage() {}

func (x *OperationDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDispatch.ProtoReflect.Descriptor instead.
func (*OperationDispatch) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *OperationDispatch) GetPermit() *OperationPermit {
	if x != nil {
		return x.Permit
	}
	return nil
}

func (x *OperationDispatch) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

// Broker → agent (CONTROL): terminate the session now. Sub-second delivery is
// the T-2b latency requirement; the contract guarantee here is that Kill is a
// CONTROL payload and can never sit behind DATA backpressure.
type Kill struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KillReason          string                 `protobuf:"bytes,2,opt,name=kill_reason,json=killReason,proto3" json:"kill_reason,omitempty"`
	IssuedAtEpochMillis int64                  `protobuf:"varint,3,opt,name=issued_at_epoch_millis,json=issuedAtEpochMillis,proto3" json:"issued_at_epoch_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Kill) Reset() {
	*x = Kill{}
	mi := &file_remote_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kill) ProtoMessage() {}

func (x *Kill) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kill.ProtoReflect.Descriptor instead.
func (*Kill) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *Kill) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Kill) GetKillReason() string {
	if x != nil {
		return x.KillReason
	}
	return ""
}

func (x *Kill) GetIssuedAtEpochMillis() int64 {
	if x != nil {
		return x.IssuedAtEpochMillis
	}
	return 0
}

// Control-plane audit event — metadata + content hash, NEVER raw payload.
type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	EpochMillis   int64                  `protobuf:"varint,4,opt,name=epoch_millis,json=epochMillis,proto3" json:"epoch_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_remote_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *AuditEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *AuditEvent) GetEpochMillis() int64 {
	if x != nil {
		return x.EpochMillis
	}
	return 0
}

// Liveness + lease propagation (both channels). Scheduling semantics are T-2b.
type Heartbeat struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalMillis   int64                  `protobuf:"varint,1,opt,name=heartbeat_interval_millis,json=heartbeatIntervalMillis,proto3" json:"heartbeat_interval_millis,omitempty"`
	LeaseExpiresAtEpochMillis int64                  `protobuf:"varint,2,opt,name=lease_expires_at_epoch_millis,json=leaseExpiresAtEpochMillis,proto3" json:"lease_expires_at_epoch_millis,omitempty"`
	ProtocolVersion           string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_remote_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *Heartbeat) GetHeartbeatIntervalMillis() int64 {
	if x != nil {
		return x.HeartbeatIntervalMillis
	}
	return 0
}

func (x *Heartbeat) GetLeaseExpiresAtEpochMillis() int64 {
	if x != nil {
		return x.LeaseExpiresAtEpochMillis
	}
	return 0
}

func (x *Heartbeat) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

// DATA-plane frame. Declared in T-2a (field numbers finalized); carries no
// business semantics until T-2b/T-4. T-2b enforces a max frame byte size at
// the stream layer (no decode-time size guard exists in T-2a — no config yet).
type DataFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	FrameSeq      int64                  `protobuf:"varint,2,opt,name=frame_seq,json=frameSeq,proto3" json:"frame_seq,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	EndStream     bool                   `protobuf:"varint,5,opt,name=end_stream,json=endStream,proto3" json:"end_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFrame) Reset() {
	*x = DataFrame{}
	mi := &file_remote_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFrame) ProtoMessage() {}

func (x *DataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFrame.ProtoReflect.Descriptor instead.
func (*DataFrame) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *DataFrame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *DataFrame) GetFrameSeq() int64 {
	if x != nil {
		return x.FrameSeq
	}
	return 0
}

func (x *DataFrame) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DataFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataFrame) GetEndStream() bool {
	if x != nil {
		return x.EndStream
	}
	return false
}

// Structured error (both channels) — avoids ad-hoc status strings later.
// detail is internal/debug only; never secrets, never raw session content.
type ErrorFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_remote_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_remote_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_remote_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorFrame) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorFrame) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorFrame) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_remote_bridge_proto protoreflect.FileDescriptor

const file_remote_bridge_proto_rawDesc = "" +
	"\n" +
	"\x13remote_bridge.proto\x12\x1dendpointadmin.remotebridge.v1\"\xd0\v\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12M\n" +
	"\fchannel_type\x18\x03 \x01(\x0e2*.endpointadmin.remotebridge.v1.ChannelTypeR\vchannelType\x12\x1b\n" +
	"\tframe_seq\x18\x04 \x01(\x03R\bframeSeq\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\tR\bstreamId\x12/\n" +
	"\x14sent_at_epoch_millis\x18\x06 \x01(\x03R\x11sentAtEpochMillis\x12L\n" +
	"\vagent_hello\x18\n" +
	" \x01(\v2).endpointadmin.remotebridge.v1.AgentHelloH\x00R\n" +
	"agentHello\x12X\n" +
	"\x0fsession_request\x18\v \x01(\v2-.endpointadmin.remotebridge.v1.SessionRequestH\x00R\x0esessionRequest\x12U\n" +
	"\x0econsent_prompt\x18\f \x01(\v2,.endpointadmin.remotebridge.v1.ConsentPromptH\x00R\rconsentPrompt\x12U\n" +
	"\x0econsent_result\x18\r \x01(\v2,.endpointadmin.remotebridge.v1.ConsentResultH\x00R\rconsentResult\x12^\n" +
	"\x11operation_request\x18\x0e \x01(\v2/.endpointadmin.remotebridge.v1.OperationRequestH\x00R\x10operationRequest\x12[\n" +
	"\x10operation_permit\x18\x0f \x01(\v2..endpointadmin.remotebridge.v1.OperationPermitH\x00R\x0foperationPermit\x129\n" +
	"\x04kill\x18\x10 \x01(\v2#.endpointadmin.remotebridge.v1.KillH\x00R\x04kill\x12L\n" +
	"\vaudit_event\x18\x11 \x01(\v2).endpointadmin.remotebridge.v1.AuditEventH\x00R\n" +
	"auditEvent\x12H\n" +
	"\theartbeat\x18\x12 \x01(\v2(.endpointadmin.remotebridge.v1.HeartbeatH\x00R\theartbeat\x12I\n" +
	"\n" +
	"data_frame\x18\x13 \x01(\v2(.endpointadmin.remotebridge.v1.DataFrameH\x00R\tdataFrame\x12A\n" +
	"\x05error\x18\x14 \x01(\v2).endpointadmin.remotebridge.v1.ErrorFrameH\x00R\x05error\x12a\n" +
	"\x12operation_dispatch\x18\x15 \x01(\v20.endpointadmin.remotebridge.v1.OperationDispatchH\x00R\x11operationDispatch\x12e\n" +
	"\x14device_key_challenge\x18\x16 \x01(\v21.endpointadmin.remotebridge.v1.DeviceKeyChallengeH\x00R\x12deviceKeyChallenge\x12\x84\x01\n" +
	"\x1fdevice_key_attestation_response\x18\x17 \x01(\v2;.endpointadmin.remotebridge.v1.DeviceKeyAttestationResponseH\x00R\x1cdeviceKeyAttestationResponseB\t\n" +
	"\apayload\"\x99\x02\n" +
	"\x12DeviceKeyChallenge\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1b\n" +
	"\tnonce_b64\x18\x02 \x01(\tR\bnonceB64\x123\n" +
	"\x16issued_at_epoch_millis\x18\x03 \x01(\x03R\x13issuedAtEpochMillis\x125\n" +
	"\x17expires_at_epoch_millis\x18\x04 \x01(\x03R\x14expiresAtEpochMillis\x12,\n" +
	"\x12transport_peer_key\x18\x05 \x01(\tR\x10transportPeerKey\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\"\xd2\x04\n" +
	"\x1cDeviceKeyAttestationResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12+\n" +
	"\x12device_key_pub_b64\x18\x03 \x01(\tR\x0fdeviceKeyPubB64\x12\x1c\n" +
	"\n" +
	"ak_pub_b64\x18\x04 \x01(\tR\bakPubB64\x12\x1e\n" +
	"\vak_name_b64\x18\x05 \x01(\tR\takNameB64\x12\x1c\n" +
	"\n" +
	"ek_pub_b64\x18\x06 \x01(\tR\bekPubB64\x12\x1e\n" +
	"\vek_cert_b64\x18\a \x01(\tR\tekCertB64\x12)\n" +
	"\x11ek_cert_chain_b64\x18\b \x03(\tR\x0eekCertChainB64\x12(\n" +
	"\x10certify_info_b64\x18\t \x01(\tR\x0ecertifyInfoB64\x12&\n" +
	"\x0fcertify_sig_b64\x18\n" +
	" \x01(\tR\rcertifySigB64\x12\x1b\n" +
	"\tquote_b64\x18\v \x01(\tR\bquoteB64\x12\"\n" +
	"\rquote_sig_b64\x18\f \x01(\tR\vquoteSigB64\x12.\n" +
	"\x13binding_context_b64\x18\r \x01(\tR\x11bindingContextB64\x12+\n" +
	"\x12device_key_sig_b64\x18\x0e \x01(\tR\x0fdeviceKeySigB64\x123\n" +
	"\x16signed_at_epoch_millis\x18\x0f \x01(\x03R\x13signedAtEpochMillis\"\xc2\x02\n" +
	"\n" +
	"AgentHello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12)\n" +
	"\x10cert_fingerprint\x18\x03 \x01(\tR\x0fcertFingerprint\x128\n" +
	"\x18attestation_evidence_b64\x18\x04 \x01(\tR\x16attestationEvidenceB64\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\x12b\n" +
	"\x17advertised_capabilities\x18\x06 \x03(\x0e2).endpointadmin.remotebridge.v1.CapabilityR\x16advertisedCapabilities\"\xf1\x01\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12)\n" +
	"\x10operator_subject\x18\x03 \x01(\tR\x0foperatorSubject\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12`\n" +
	"\x16requested_capabilities\x18\x05 \x03(\x0e2).endpointadmin.remotebridge.v1.CapabilityR\x15requestedCapabilities\"\xf9\x01\n" +
	"\rConsentPrompt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x15operator_display_name\x18\x02 \x01(\tR\x13operatorDisplayName\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12M\n" +
	"\fcapabilities\x18\x04 \x03(\x0e2).endpointadmin.remotebridge.v1.CapabilityR\fcapabilities\x12.\n" +
	"\x13expiry_epoch_millis\x18\x05 \x01(\x03R\x11expiryEpochMillis\"\xef\x01\n" +
	"\rConsentResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\x12>\n" +
	"\x1bwindows_interactive_session\x18\x03 \x01(\tR\x19windowsInteractiveSession\x125\n" +
	"\x17granted_at_epoch_millis\x18\x04 \x01(\x03R\x14grantedAtEpochMillis\x12.\n" +
	"\x13expiry_epoch_millis\x18\x05 \x01(\x03R\x11expiryEpochMillis\"\xc3\x01\n" +
	"\x10OperationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12J\n" +
	"\toperation\x18\x03 \x01(\x0e2,.endpointadmin.remotebridge.v1.WireOperationR\toperation\x12!\n" +
	"\fcommand_line\x18\x04 \x01(\tR\vcommandLine\"\xbf\x04\n" +
	"\x0fOperationPermit\x12\x10\n" +
	"\x03alg\x18\x01 \x01(\tR\x03alg\x12\x10\n" +
	"\x03kid\x18\x02 \x01(\tR\x03kid\x12%\n" +
	"\x0epermit_version\x18\x03 \x01(\x05R\rpermitVersion\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\tR\rpolicyVersion\x12\x1f\n" +
	"\vdecision_id\x18\x05 \x01(\tR\n" +
	"decisionId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12!\n" +
	"\foperation_id\x18\a \x01(\tR\voperationId\x12\x1b\n" +
	"\tdevice_id\x18\b \x01(\tR\bdeviceId\x12)\n" +
	"\x10operator_subject\x18\t \x01(\tR\x0foperatorSubject\x12I\n" +
	"\n" +
	"capability\x18\n" +
	" \x01(\x0e2).endpointadmin.remotebridge.v1.CapabilityR\n" +
	"capability\x12!\n" +
	"\fcommand_hash\x18\v \x01(\tR\vcommandHash\x123\n" +
	"\x16issued_at_epoch_millis\x18\f \x01(\x03R\x13issuedAtEpochMillis\x125\n" +
	"\x17expires_at_epoch_millis\x18\r \x01(\x03R\x14expiresAtEpochMillis\x12\x10\n" +
	"\x03seq\x18\x0e \x01(\x03R\x03seq\x12#\n" +
	"\rsignature_b64\x18\x0f \x01(\tR\fsignatureB64\"~\n" +
	"\x11OperationDispatch\x12F\n" +
	"\x06permit\x18\x01 \x01(\v2..endpointadmin.remotebridge.v1.OperationPermitR\x06permit\x12!\n" +
	"\fcommand_line\x18\x02 \x01(\tR\vcommandLine\"{\n" +
	"\x04Kill\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vkill_reason\x18\x02 \x01(\tR\n" +
	"killReason\x123\n" +
	"\x16issued_at_epoch_millis\x18\x03 \x01(\x03R\x13issuedAtEpochMillis\"\x90\x01\n" +
	"\n" +
	"AuditEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12!\n" +
	"\fepoch_millis\x18\x04 \x01(\x03R\vepochMillis\"\xb4\x01\n" +
	"\tHeartbeat\x12:\n" +
	"\x19heartbeat_interval_millis\x18\x01 \x01(\x03R\x17heartbeatIntervalMillis\x12@\n" +
	"\x1dlease_expires_at_epoch_millis\x18\x02 \x01(\x03R\x19leaseExpiresAtEpochMillis\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\"\xa1\x01\n" +
	"\tDataFrame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tframe_seq\x18\x02 \x01(\x03R\bframeSeq\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"end_stream\x18\x05 \x01(\bR\tendStream\"V\n" +
	"\n" +
	"ErrorFrame\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable*R\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tVIEW_ONLY\x10\x01\x12\x13\n" +
	"\x0fCONSTRAINED_PTY\x10\x02\"\x04\b\x03\x10\x0f*W\n" +
	"\rWireOperation\x12\x1e\n" +
	"\x1aWIRE_OPERATION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSCREEN_VIEW\x10\x01\x12\x0f\n" +
	"\vPTY_COMMAND\x10\x02\"\x04\b\x03\x10\x0f*B\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCONTROL\x10\x01\x12\b\n" +
	"\x04DATA\x10\x022\xcd\x01\n" +
	"\fRemoteBridge\x12_\n" +
	"\aConnect\x12'.endpointadmin.remotebridge.v1.Envelope\x1a'.endpointadmin.remotebridge.v1.Envelope(\x010\x01\x12\\\n" +
	"\x04Data\x12'.endpointadmin.remotebridge.v1.Envelope\x1a'.endpointadmin.remotebridge.v1.Envelope(\x010\x01B\x82\x01\n" +
	"3com.example.endpointadmin.remoteaccess.bridge.protoB\x11RemoteBridgeProtoP\x01Z6platform-agent/internal/remotebridge/pb;remotebridgepbb\x06proto3"

var (
	file_remote_bridge_proto_rawDescOnce sync.Once
	file_remote_bridge_proto_rawDescData []byte
)

func file_remote_bridge_proto_rawDescGZIP() []byte {
	file_remote_bridge_proto_rawDescOnce.Do(func() {
		file_remote_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_bridge_proto_rawDesc), len(file_remote_bridge_proto_rawDesc)))
	})
	return file_remote_bridge_proto_rawDescData
}

var file_remote_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_remote_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_remote_bridge_proto_goTypes = []any{
	(Capability)(0),                      // 0: endpointadmin.remotebridge.v1.Capability
	(WireOperation)(0),                   // 1: endpointadmin.remotebridge.v1.WireOperation
	(ChannelType)(0),                     // 2: endpointadmin.remotebridge.v1.ChannelType
	(*Envelope)(nil),                     // 3: endpointadmin.remotebridge.v1.Envelope
	(*DeviceKeyChallenge)(nil),           // 4: endpointadmin.remotebridge.v1.DeviceKeyChallenge
	(*DeviceKeyAttestationResponse)(nil), // 5: endpointadmin.remotebridge.v1.DeviceKeyAttestationResponse
	(*AgentHello)(nil),                   // 6: endpointadmin.remotebridge.v1.AgentHello
	(*SessionRequest)(nil),               // 7: endpointadmin.remotebridge.v1.SessionRequest
	(*ConsentPrompt)(nil),                // 8: endpointadmin.remotebridge.v1.ConsentPrompt
	(*ConsentResult)(nil),                // 9: endpointadmin.remotebridge.v1.ConsentResult
	(*OperationRequest)(nil),             // 10: endpointadmin.remotebridge.v1.OperationRequest
	(*OperationPermit)(nil),              // 11: endpointadmin.remotebridge.v1.OperationPermit
	(*OperationDispatch)(nil),            // 12: endpointadmin.remotebridge.v1.OperationDispatch
	(*Kill)(nil),                         // 13: endpointadmin.remotebridge.v1.Kill
	(*AuditEvent)(nil),                   // 14: endpointadmin.remotebridge.v1.AuditEvent
	(*Heartbeat)(nil),                    // 15: endpointadmin.remotebridge.v1.Heartbeat
	(*DataFrame)(nil),                    // 16: endpointadmin.remotebridge.v1.DataFrame
	(*ErrorFrame)(nil),                   // 17: endpointadmin.remotebridge.v1.ErrorFrame
}
var file_remote_bridge_proto_depIdxs = []int32{
	2,  // 0: endpointadmin.remotebridge.v1.Envelope.channel_type:type_name -> endpointadmin.remotebridge.v1.ChannelType
	6,  // 1: endpointadmin.remotebridge.v1.Envelope.agent_hello:type_name -> endpointadmin.remotebridge.v1.AgentHello
	7,  // 2: endpointadmin.remotebridge.v1.Envelope.session_request:type_name -> endpointadmin.remotebridge.v1.SessionRequest
	8,  // 3: endpointadmin.remotebridge.v1.Envelope.consent_prompt:type_name -> endpointadmin.remotebridge.v1.ConsentPrompt
	9,  // 4: endpointadmin.remotebridge.v1.Envelope.consent_result:type_name -> endpointadmin.remotebridge.v1.ConsentResult
	10, // 5: endpointadmin.remotebridge.v1.Envelope.operation_request:type_name -> endpointadmin.remotebridge.v1.OperationRequest
	11, // 6: endpointadmin.remotebridge.v1.Envelope.operation_permit:type_name -> endpointadmin.remotebridge.v1.OperationPermit
	13, // 7: endpointadmin.remotebridge.v1.Envelope.kill:type_name -> endpointadmin.remotebridge.v1.Kill
	14, // 8: endpointadmin.remotebridge.v1.Envelope.audit_event:type_name -> endpointadmin.remotebridge.v1.AuditEvent
	15, // 9: endpointadmin.remotebridge.v1.Envelope.heartbeat:type_name -> endpointadmin.remotebridge.v1.Heartbeat
	16, // 10: endpointadmin.remotebridge.v1.Envelope.data_frame:type_name -> endpointadmin.remotebridge.v1.DataFrame
	17, // 11: endpointadmin.remotebridge.v1.Envelope.error:type_name -> endpointadmin.remotebridge.v1.ErrorFrame
	12, // 12: endpointadmin.remotebridge.v1.Envelope.operation_dispatch:type_name -> endpointadmin.remotebridge.v1.OperationDispatch
	4,  // 13: endpointadmin.remotebridge.v1.Envelope.device_key_challenge:type_name -> endpointadmin.remotebridge.v1.DeviceKeyChallenge
	5,  // 14: endpointadmin.remotebridge.v1.Envelope.device_key_attestation_response:type_name -> endpointadmin.remotebridge.v1.DeviceKeyAttestationResponse
	0,  // 15: endpointadmin.remotebridge.v1.AgentHello.advertised_capabilities:type_name -> endpointadmin.remotebridge.v1.Capability
	0,  // 16: endpointadmin.remotebridge.v1.SessionRequest.requested_capabilities:type_name -> endpointadmin.remotebridge.v1.Capability
	0,  // 17: endpointadmin.remotebridge.v1.ConsentPrompt.capabilities:type_name -> endpointadmin.remotebridge.v1.Capability
	1,  // 18: endpointadmin.remotebridge.v1.OperationRequest.operation:type_name -> endpointadmin.remotebridge.v1.WireOperation
	0,  // 19: endpointadmin.remotebridge.v1.OperationPermit.capability:type_name -> endpointadmin.remotebridge.v1.Capability
	11, // 20: endpointadmin.remotebridge.v1.OperationDispatch.permit:type_name -> endpointadmin.remotebridge.v1.OperationPermit
	3,  // 21: endpointadmin.remotebridge.v1.RemoteBridge.Connect:input_type -> endpointadmin.remotebridge.v1.Envelope
	3,  // 22: endpointadmin.remotebridge.v1.RemoteBridge.Data:input_type -> endpointadmin.remotebridge.v1.Envelope
	3,  // 23: endpointadmin.remotebridge.v1.RemoteBridge.Connect:output_type -> endpointadmin.remotebridge.v1.Envelope
	3,  // 24: endpointadmin.remotebridge.v1.RemoteBridge.Data:output_type -> endpointadmin.remotebridge.v1.Envelope
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_remote_bridge_proto_init() }
func file_remote_bridge_proto_init() {
	if File_remote_bridge_proto != nil {
		return
	}
	file_remote_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_AgentHello)(nil),
		(*Envelope_SessionRequest)(nil),
		(*Envelope_ConsentPrompt)(nil),
		(*Envelope_ConsentResult)(nil),
		(*Envelope_OperationRequest)(nil),
		(*Envelope_OperationPermit)(nil),
		(*Envelope_Kill)(nil),
		(*Envelope_AuditEvent)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_DataFrame)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_OperationDispatch)(nil),
		(*Envelope_DeviceKeyChallenge)(nil),
		(*Envelope_DeviceKeyAttestationResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_bridge_proto_rawDesc), len(file_remote_bridge_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_bridge_proto_goTypes,
		DependencyIndexes: file_remote_bridge_proto_depIdxs,
		EnumInfos:         file_remote_bridge_proto_enumTypes,
		MessageInfos:      file_remote_bridge_proto_msgTypes,
	}.Build()
	File_remote_bridge_proto = out.File
	file_remote_bridge_proto_goTypes = nil
	file_remote_bridge_proto_depIdxs = nil
}
