//go:build windows

// Code generated by AG-029 WinTrust binding; DO NOT EDIT.

package selfupdate

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var (
	modwintrust                        = windows.NewLazySystemDLL("wintrust.dll")
	procWTHelperProvDataFromStateData  = modwintrust.NewProc("WTHelperProvDataFromStateData")
	procWTHelperGetProvSignerFromChain = modwintrust.NewProc("WTHelperGetProvSignerFromChain")
)

func wTHelperProvDataFromStateData(state windows.Handle) uintptr {
	r1, _, _ := syscall.SyscallN(procWTHelperProvDataFromStateData.Addr(), uintptr(state))
	return r1
}

func wTHelperGetProvSignerFromChain(provData uintptr, signerIndex uint32, counterSigner bool, counterSignerIndex uint32) *cryptProviderSgnr {
	var isCounterSigner uintptr
	if counterSigner {
		isCounterSigner = 1
	}
	r1, _, _ := syscall.SyscallN(
		procWTHelperGetProvSignerFromChain.Addr(),
		provData,
		uintptr(signerIndex),
		isCounterSigner,
		uintptr(counterSignerIndex),
	)
	if r1 == 0 {
		return nil
	}
	// WinTrust owns this process-local provider pointer until StateAction=CLOSE.
	// It is read synchronously by the caller and is never retained in Go state.
	return (*cryptProviderSgnr)(unsafe.Add(nil, int(r1)))
}

// cryptProviderSgnr mirrors the prefix of WinTrust's CRYPT_PROVIDER_SGNR. AG-029
// only reads sftVerifyAsOf + countersigner count to preserve Authenticode
// timestamp semantics after WinVerifyTrust has already validated the signature.
type cryptProviderSgnr struct {
	CbStruct          uint32
	SftVerifyAsOf     windows.Filetime
	CsCertChain       uint32
	PasCertChain      uintptr
	DwSignerType      uint32
	PsSigner          uintptr
	DwError           uint32
	CsCounterSigners  uint32
	PasCounterSigners uintptr
	PChainContext     uintptr
}
